services:
  app:
    build:
      context: .
      dockerfile: .docker/app/Dockerfile-dev
      args:
        - UID=${UID:-1000}
        - GID=${GID:-1000}
    volumes:
      - ./app:/app
    ports:
      - 8080:8080
      - 8081:8081